language: julia
os:
  - linux
julia:
  - 1.5
  - nightly
notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
            Pkg.instantiate();
            Pkg.develop(PackageSpec(path=pwd()));'
        - travis_wait 30 julia --project=docs --color=yes docs/make.jl
      after_success: skip
