language: julia

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
            Pkg.add("Documenter");
            Pkg.add(PackageSpec(url="https://github.com/arzwa/PhyloTrees.jl"));
            Pkg.add(PackageSpec(url="https://github.com/arzwa/ConsensusTrees.jl"));
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
